### ISSUE TITLE
The POM for com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta is missing

### ISSUE THREAD

**Issue by fazeelT** [GoogleCloudPlatform/prediction-try-java-python#11]
Hello,

I am getting this error from Maven....

>mvn -e gae:unpack
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building try-prediction-java 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-gae-plugin:0.9.0:unpack (default-cli) > initialize @ gae-java >>>
[INFO]
[INFO] <<< maven-gae-plugin:0.9.0:unpack (default-cli) < initialize @ gae-java <<<
[WARNING] The POM for com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.982 s
[INFO] Finished at: 2016-01-05T14:45:59-06:00
[INFO] Final Memory: 7M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gae-java: Could not resolve dependencies for project com.google.tryPredictionJava:gae-java:war:1.0-SNAPSHOT: Failure to find com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project gae-java: Could not resolve dependencies for project com.google.tryPredictionJava:gae-java:war:1.0-SNAPSHOT: Failure to find com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.google.tryPredictionJava:gae-java:war:1.0-SNAPSHOT: Failure to find com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.google.apis:google-api-services-prediction:jar:v1.4-1.3.0-beta in http://mavenrepo.google-api-java-client.googlecode.com/hg was cached in the local repository, resolution will not be reattempted until the update interval of google-api-services has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 27 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by dsx1986** [comment]
same error, anybody has solution?

**Comment by dheerajmadan** [comment]
Hi

Did this issue resolved, I am also getting same error...

**Comment by fazeelT** [comment]
For me the directory ..../python/dist-packages/roshelper contained
__init__.py node.py partialnode.py ... __init__.py is trying to use node.py
which is in same directory. To solve this i replaced "from node import
Node" to "from roshelper.node import Node" in file __init__.py

I had same error with some other modules so i just added folder-name.* in
import statement that throw error.

Thanks

**Comment by dheerajmadan** [comment]
Well, I am trying to build gae-java project not python one, you were able to resolve dependency?

**Comment by fazeelT** [comment]
oops i mixed up.

I think this can be solve by changing maven repo link.
http://mavenrepo.google-api-java-client.googlecode.com/hg does not contain
the library.

**Comment by dheerajmadan** [comment]
Thanks :) You know which one contains dependency, I am not able to get link

**Comment by fazeelT** [comment]
Try this repo: https://mvnrepository.com/artifact/com.google.apis/google-api-services-prediction/v1.5-rev26-1.13.2-beta
